### PR TITLE
fix(barSeries): error rendering bars with negative log scale

### LINKED ISSUE #607: Band charts should show y0 value in tooltip, be treated as a single series
I'm exploring how we will visualize bounded data in Lens, and found this issue. As seen in [this band chart](https://codesandbox.io/s/focused-field-tpjm0), the lower value is not shown in the tooltip.

Screenshot 2020-03-25 17 46 28

Also, I would like to treat a band as a single series, not as a two series. It doesn't seem like it's possible to get the series name to only show up once in the legend, even using code like:

```
          y0AccessorFormat={''}
          y1AccessorFormat={''}
```

### LINKED ISSUE #2406: Log scale uses wrong baseline for negative domains
When using a logarithmic scale with all negative values, the areas or bars are rendered from the bottom up (towards from `0`) instead of the top down (aways from `0`)

image

The expected behavior should match that of the linear scales, as shown below.

image

### LINKED ISSUE #2408: Banded `BarSeries` not showing lower value in tooltip
When using `y1Accessors` and `y0Accessors`, the tooltip values exclude the value from the `y0Accessors`.

image

### PR DESCRIPTION
**Pull request by nickofthyme**
## Summary

This PR mainly fixes the rendering of bars on a negative log scale. Also fixes the tooltip for banded bar charts.

Zight Recording 2024-04-11 at 10 27 05 AM

In addition this PR fixes some other issues including
- Banded bar charts missing lower bound series in tooltip and legend
- Wrong highlighting of tooltips value and highlighted bar geometries, particularly for banded bar charts.
- Banded series items in tooltip were being shuffled according to the distance to the cursor position. Now I pre-sort them to not abruptly switch.
- The Chrome bug from #1053 associated with filling areas containing sharp corners, is now fixed and since using the shared `getY1ScaledValueFn` and `getY0ScaledValueFn` functions I just removed this logic to avoid checking.

## Details

The bar geometry logic was using custom logic to handle the scaled `y1` and `y0` values, this was imperfect. This same issue was not present with `AreaSeries` as we had already addressed it. Using the same logic from area geometries fixed the issue.

Secondly, while testing the above fix for banded `BarSeries`, I noticed that the tooltip never showed the `lower` bound item on the tooltip. This again only an issue for bar charts. The issue is that unlike the `AreaSeries` the `BarSeries` geometry is a single geometry for the upper and lower whereas the area is 2 points. So simply adding the `y0` geometry to the `indexedGeometryMap` solved the issue, see bed2b45.

## Issues

fix #2406, fix #2408, fix #607

### Checklist

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [ ] Unit tests have been added or updated to match the most common scenarios
- [x] The proper documentation and/or storybook story has been added or updated

### CODE REVIEW

**Comment by nickofthyme** [comment]
buildkite update screenshots

File: packages/charts/src/chart_types/xy_chart/rendering/bars.ts [hunk 1]
```diff
@@ -143,6 +148,24 @@ export function renderBars(
...
+          y: getDatumYValue(datum, true, isBandedSpec, stackMode),
+          mark: null,
+          accessor: BandedAccessorType.Y0,
+          datum: datum.datum,
+        },
+        bandedY: finalY1,
+      });
+
+      barGeometry.bandedY = finalY0;
+    }
```
Comment (nickofthyme) [inline packages/charts/src/chart_types/xy_chart/rendering/bars.ts:167]: Adds lower (`y0`) tooltip and legend value.

File: packages/charts/src/chart_types/xy_chart/rendering/utils.ts [hunk 2]
```diff
@@ -136,8 +137,22 @@ export function isPointOnGeometry(
...
+  if (!isWithinRange([x, x + width])(xCoordinate)) return false;
+
+  if (isBandedSpec) {
+    if (bandedY === undefined) return false;
+
+    const rangeUtils = inRange(y, bandedY);
+    return accessor === 'y0' ? rangeUtils.firstHalf(yCoordinate) : rangeUtils.firstHalf(yCoordinate);
+  }
+
+  return isWithinRange([y, y + height])(yCoordinate);
```
Comment (nickofthyme) [inline packages/charts/src/chart_types/xy_chart/rendering/utils.ts:155]: Only highlights the closest half of banded bars in tooltip.

Zight Recording 2024-04-26 at 03 03 07 PM

File: packages/charts/src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.ts [hunk 3]
```diff
@@ -129,58 +129,63 @@ function getTooltipAndHighlightFromValue(
...
-
-    xValues.add(indexedGeometry.value.x);
-
-    return [...acc, formattedTooltip];
-  }, []);
+  const values = matchingGeoms
+    .toSorted((a, b) => {
+      // presort matchingGeoms to group by series then y value to prevent flipping
+      return b.seriesIdentifier.key.localeCompare(a.seriesIdentifier.key) || b.value.y - a.value.y;
+    })
```
Comment (nickofthyme) [inline packages/charts/src/chart_types/xy_chart/state/selectors/get_tooltip_values_highlighted_geoms.ts:136]: Prevents `lower` and `upper` tooltip items from swapping based on cursor position. Code in `reduce` below is unchanged.

Zight Recording 2024-04-26 at 03 04 49 PM

File: packages/charts/src/utils/common.tsx [hunk 4]
```diff
@@ -732,6 +732,32 @@ export const isWithinRange = (range: [number, number], exclusive = false) => {
...
+      return start === min ? isHalfFromMin(n) : isHalfFromMax(n);
+    },
+    /**
+     * Returns true if values are within the last half of range, from end halfway to start
+     */
+    lastHalf: (n: number) => {
+      return end === max ? isHalfFromMax(n) : isHalfFromMin(n);
+    },
+  };
+};
```
Comment (nickofthyme) [inline packages/charts/src/utils/common.tsx:759]: Utility to simplify checking if a value is in the first or last half of a range relative to the start/end regardless of polarity.

File: packages/charts/src/utils/geometry.ts [hunk 5]
```diff
@@ -103,6 +103,7 @@ export interface BarGeometry {
   value: GeometryValue;
   seriesStyle: BarSeriesStyle;
   panel: Dimensions;
+  bandedY?: number;
```
Comment (nickofthyme) [inline packages/charts/src/utils/geometry.ts:106]: We need to know what the other part of the range, as these are independently checked if cursor is over geometry.

File: packages/charts/src/chart_types/xy_chart/rendering/bars.ts [hunk 6]
```diff
@@ -43,40 +43,45 @@ export function renderBars(
...
+    const finiteHeight = y0Scaled - y1Scaled || 0;
     const absHeight = Math.abs(finiteHeight);
-    const height = absHeight === 0 ? absHeight : Math.max(minBarHeight, absHeight); // extend nonzero bars
-    const heightExtension = height - absHeight;
+    const crossesZero = y0 && y1 && isWithinRange([y0, y1])(0);
+    const adjustedHeight =
+      absHeight === 0
+        ? absHeight
+        : // extends nonzero bar height - doubled for bars crossing 0
+          Math.max((crossesZero ? 2 : 1) * minBarHeight, absHeight);
```
Comment (nickofthyme) [inline packages/charts/src/chart_types/xy_chart/rendering/bars.ts:75]: Using `minBarHeight` on banded bars is a little strange, but for small value of say `~2px` it's ok.

The issue is that the `minBarHeight` can be applied away from the baseline, altering the accuracy of the scale.

Additionally, when a banded bar crosses the `0` baseline, we only applied the `minBarHeight` to one side, which looks very strange. This code fixes this issue but simply doubling the `minBarHeight` for cases where the `minBarHeight` is applied and where the bar crosses `0`.

File: packages/charts/src/chart_types/xy_chart/rendering/bars.ts [hunk 7]
```diff
@@ -43,40 +43,45 @@ export function renderBars(
...
+    const y1Extension = (adjustedHeight - absHeight) / (crossesZero ? 2 : 1);
+    const y0Extension = crossesZero ? y1Extension : 0;
     const isUpsideDown = finiteHeight < 0;
-    const finiteY = Number.isNaN(y0Scaled + rawY) ? 0 : rawY;
-    const y = isUpsideDown ? finiteY - height + heightExtension : finiteY - heightExtension;
+    const height = isUpsideDown ? -adjustedHeight : adjustedHeight;
```
Comment (nickofthyme) [inline packages/charts/src/chart_types/xy_chart/rendering/bars.ts:79]: Previously we were basically swapping `y1` and `y0` to render an adjusted bar to always render top down. This was very confusing but makes sense, however attempting to alter the highlighter logic for this case was extremely difficult and after many tries I gave up.

Now, the `y0` and `y1` values are what they are, we compute the absolute `height` and apply the original sign to the height to indicate that the bar is upsidedown. This allow us to check in the highlighter for this case and handle it accordingly. The canas renderer correctly renders the bar without translating this negative height.

This also helps to check for cursor over geometry.

File: packages/charts/src/chart_types/xy_chart/rendering/bars.ts [hunk 8]
```diff
@@ -143,6 +148,24 @@ export function renderBars(
...
+          x: datum.x,
+          y: getDatumYValue(datum, true, isBandedSpec, stackMode),
+          mark: null,
+          accessor: BandedAccessorType.Y0,
+          datum: datum.datum,
+        },
+        bandedY: finalY1,
+      });
+
+      barGeometry.bandedY = finalY0;
```
Comment (nickofthyme) [inline packages/charts/src/chart_types/xy_chart/rendering/bars.ts:166]: Only need this value if it is a banded spec

File: packages/charts/src/chart_types/xy_chart/renderer/dom/highlighter.tsx [hunk 9]
```diff
@@ -100,13 +103,14 @@ class HighlighterComponent extends React.Component<HighlighterProps> {
...
+
           return (
             <rect
               key={i}
               x={x}
-              y={y}
+              y={geom.height < 0 ? (accessor === 'y1' ? y + geom.height : y) : accessor === 'y1' ? y : y - geom.height}
               width={geom.width}
-              height={geom.height}
+              height={Math.abs(geom.height)}
```
Comment (nickofthyme) [inline packages/charts/src/chart_types/xy_chart/renderer/dom/highlighter.tsx:113]: Transforms geoms to correctly render negative height svg for highlighting either `y0` or `y1` bars.

**Review by nickofthyme — COMMENTED** [review]
Just leaving comments to explain specific code changes.

**Comment by nickofthyme** [comment]
buildkite update screenshots

File: packages/charts/src/chart_types/xy_chart/rendering/utils.ts (hunk 2 above)
Comment (nickofthyme) [reply packages/charts/src/chart_types/xy_chart/rendering/utils.ts]: Removed. No longer applies

**Comment by nickofthyme** [comment]
buildkite update screenshots
