### PR TITLE
fix(rendering): clip at panel sizes on small multiples

### LINKED ISSUE #1650: Wrong area clippings when using small multiples
**Describe the issue**

When rendering small multiples, the clipping area of the single panel is not respected, and charts like the one in the screenshot overflow the chart panel space.

**To Reproduce**
1. Go to https://codesandbox.io/s/ancient-shadow-b5e51n?file=/src/App.tsx

**Expected behaviour**
Independentely from the used scale, the clipping area should reflect the panel dimension.

**Screenshots**
Screenshot 2022-04-15 at 10 26 33

**Version (please complete the following information):**

 - Elastic Charts: verified in `45.1.1` but existing also in `40.3.0` (Kibana `7.17.0`).

**Additional context**
 It looks like a regression introduced in version 30.0.0, in version 29.2.0 the chart was rendered correcrly

**Errors in browser console**
n/a

**Kibana Cross Issues**

**Checklist**

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)

### PR DESCRIPTION
**Pull request by markov00**
## Summary
We use a clipping region to avoid rendering elements outside of it.
In particular, clipping is useful when we just want to render a continuous line that goes out of the chart without the need to compute the an intermediate end point of the line crossing the chart edge.
This was used correctly with standard charts, but was not correctly computed for small multiple. This PR uses the panel dimension to compute the clipping area of each chart independently if it is on a small multiple or is just a single chart.

### Details

The bug is available in `7.17.0` in kibana and should be backported to `40.3.0`

I took the chance to clean up a a bit the code, nothing special, just a bunch of code refactoring and deletions.

## Issues

fix #1650 

### Checklist

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [x] Unit tests have been added or updated to match the most common scenarios
- [x] The proper documentation and/or storybook story has been added or updated

### CODE REVIEW

File: packages/charts/src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx [hunk 1]
```diff
@@ -130,12 +128,7 @@ class XYChartComponent extends React.Component<XYChartProps> {
 
   private drawCanvas() {
     if (this.ctx) {
-      const { renderingArea, rotation } = this.props;
-      const vertical = Math.abs(rotation) === 90;
-      const width = (vertical ? renderingArea.height : renderingArea.width) + CLIPPING_MARGINS * 2;
-      const height = (vertical ? renderingArea.width : renderingArea.height) + CLIPPING_MARGINS * 2;
-      const clippings = { x: -CLIPPING_MARGINS, y: -CLIPPING_MARGINS, width, height };
-      renderXYChartCanvas2d(this.ctx, this.devicePixelRatio, clippings, this.props);
+      renderXYChartCanvas2d(this.ctx, this.devicePixelRatio, this.props);
```
Comment (nickofthyme) [inline packages/charts/src/chart_types/xy_chart/renderer/canvas/xy_chart.tsx:131]: 👍🏼

**Review by nickofthyme — APPROVED** [review]
Nice quick response on this!
