### PR TITLE
fix: allow graceful error handling

### LINKED ISSUE #776: Gracefully handle bad custom domain
**Describe the bug**
When setting a custom min greater than computed max of the data, the chart will throw an error. Or similarly, when setting a custom max less than computed min of the data.

**Expected behaviour**
Renders empty chart when data is outside of custom bounds. Logs warning to console.

**Version (please complete the following information):**
 - Elastic Charts: all

**Errors in browser console**
```
node_modules\@elastic\charts\dist\chart_types\xy_chart\domains\y_domain.js:113 Uncaught Error: custom yDomain for yaxis_2e91f9d0-cd39-11ea-8e53-15bf965b677f_main_group is invalid, custom min is greater than computed max
```

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/73167

**Checklist**

- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

### PR DESCRIPTION
**Pull request by nickofthyme**
fix #776

Allow gracefully handling/catching of errors at a top level.

Now calling errors as `GracefulError` will still show in the console but return an empty chart, not a blank element.

```ts
throw new GracefulError('Something went wrong');
```

Screen Recording 2020-08-17 at 04 11 PM

### CODE REVIEW

File: src/components/error_boundary/error_boundary.tsx [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+  render() {
+    if (this.hasError) {
+      return (
+        <div className="echReactiveChart_unavailable">
+          <p>No data to display</p>
+        </div>
+      );
+    }
+
+    return <>{this.props.children}</>;
```
Comment (markov00) [inline src/components/error_boundary/error_boundary.tsx:61]: can you return directly `return this.props.children` ?

File: src/components/error_boundary/errors.ts [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+});
+/** @public */
+export type ChartTypes = $Values<typeof ErrorType>;
+
+/**
+ * Error to used to gracefully render empty chart
+ */
+export class GracefulError extends Error {
+  type = ErrorType.Graceful;
+  renderEmptyChart: boolean;
```
Comment (markov00) [inline src/components/error_boundary/errors.ts:33]: This flag is not currently used, what was the idea behind that?

Comment (nickofthyme) [reply src/components/error_boundary/errors.ts:33]: Thanks, I'll remove it for now. The idea was to allow this to be a more generic error. You could throw this error everywhere is charts and customize how the error is handled such as if it should throw, or if the chart should render empty. I think this can be discussed once we improve the error handling.

File: src/components/error_boundary/error_boundary.tsx (hunk 1 above)
Comment (nickofthyme) [reply src/components/error_boundary/error_boundary.tsx]: 446f764

File: src/components/error_boundary/errors.ts [hunk 3]
```diff
@@ -0,0 +1,43 @@
...
+ * under the License.
+ */
+
+import { $Values } from 'utility-types';
+
+export const ErrorType = Object.freeze({
+  Graceful: 'graceful' as const,
+});
+/** @public */
+export type ChartTypes = $Values<typeof ErrorType>;
```
[the remark this answers is not in the document]
Comment (nickofthyme) [reply src/components/error_boundary/errors.ts]: 446f764
