### PR TITLE
fix: set uninitialized state when removeSpec action is called

### LINKED ISSUE #738: Wrong status when removing a spec from the configuration
**Describe the bug**
When sending the `removeSpec` action due to a change in the chart configuration, the chart is in the wrong status. In particular, the state confirms that the chart `isInitialized` when it is clearly not.

**To Reproduce**
1. Use the following code to reproduce: https://codesandbox.io/s/recursing-joliot-iht2v?file=/src/App.tsx
2. Click on the text `Change bar to line`
3. See error

**Expected behaviour**

**Version (please complete the following information):**
 - Elastic Charts: 19.6.2

**Additional context**
Regression caused by #723 

**Errors in browser console**
```
Uncaught Error: Cannot compute scale for axis spec right
    at Object.computeAxisTicksDimensions (axis_utils.js:24)
    at compute_axis_ticks_dimensions.js:31
    at Array.forEach (<anonymous>)
    at compute_axis_ticks_dimensions.js:29
    at resultFuncWithRecomputations (index.js:77)
    at index.js:70
    at index.js:30
    at index.js:84
    at index.js:30
    at selector (index.js:105)
computeAxisTicksDimensions @ axis_utils.js:24
(anonymous) @ compute_axis_ticks_dimensions.js:31
(anonymous) @ compute_axis_ticks_dimensions.js:29
resultFuncWithRecomputations @ index.js:77
(anonymous) @ index.js:70
(anonymous) @ index.js:30
(anonymous) @ index.js:84
(anonymous) @ index.js:30
selector @ index.js:105
(anonymous) @ index.js:80
(anonymous) @ index.js:30
selector @ index.js:105
(anonymous) @ index.js:80
(anonymous) @ index.js:30
selector @ index.js:105
(anonymous) @ index.js:80
(anonymous) @ index.js:30
selector @ index.js:105
(anonymous) @ index.js:80
(anonymous) @ index.js:30
selector @ index.js:105
(anonymous) @ on_element_over_caller.js:56
push.../../node_modules/@elastic/charts/dist/chart_types/xy_chart/state/chart_state.js.XYAxisChartState.eventCallbacks @ chart_state.js:85
(anonymous) @ chart.js:106
dispatch @ redux.js:221
(anonymous) @ redux.js:475
(anonymous) @ spec_factory.js:36
callCallback @ react-dom.development.js:336
```

**Kibana Cross Issues**
- https://github.com/elastic/kibana/issues/70749

### PR DESCRIPTION
**Pull request by markov00**
## Summary

This commit reset the chart state to not initialized when removing a spec. After #723 PR that
reduced the number of steps on the state machine when parsing, the removeSpec action wasn't
accounted on that refactoring causing side effects when removing/switching a spec on the chart
configuration due to the state being in an wrong status.

fix #738

### Checklist

- [x] Unit tests were updated or added to match the most common scenarios

### CODE REVIEW

File: src/state/chart_state.ts [hunk 1]
```diff
@@ -320,6 +320,9 @@ export const chartStoreReducer = (chartId: string) => {
         const { [action.id]: specToRemove, ...rest } = state.specs;
         return {
           ...state,
+          specsInitialized: false,
+          chartRendered: false,
+          specParsing: true,
```
Comment (nickofthyme) [inline src/state/chart_state.ts:325]: 👍
