### PR TITLE
fix(partition): small multiples panel title color

### LINKED ISSUE #1327: Panel title color in dark mode not working
**Describe the bug**
When using partition charts and small multiples, the panel title use a default color and can't be changed. This works fine with a light/white background, but doesn't work with a dark background.

**To Reproduce**
1. Go to https://elastic.github.io/elastic-charts/?path=/story/small-multiples-alpha--sunbursts
2. Click on the Dark EUI theme
3. The panel title is basically invisible

**Expected behaviour**
The panel title should use the axis panel title style from the theme

**Screenshots**
Screenshot 2021-08-24 at 13 01 58

**Version (please complete the following information):**
 - Elastic Charts: master

**Additional context**
N/A

**Errors in browser console**
N/A

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/109639

### PR DESCRIPTION
**Pull request by markov00**
## Summary

When rendering a pie chart in small multiples, the panel title now correctly use the theme `axisPanelTitle` configuration.

image

## Details

The previous implementation made use of a static color and font for the panel title.
The code was refactored to use the `theme.axes.axisPanelTitle` fontface and size.

A small fix was also pushed to the VRT background/theme hooks to correctly pass the backgroundColor to the BackgroundProvider.

## Issues

fix #1327

### Checklist

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [x] Unit tests have been added or updated to match the most common scenarios
- [x] The proper documentation and/or storybook story has been added or updated
- [x] Visual changes have been tested with all available themes including `dark`, `light`, `eui-dark` & `eui-light`

### CODE REVIEW

File: storybook/use_base_theme.ts [hunk 1]
```diff
@@ -41,14 +39,9 @@ const themeMap = {
   [ThemeId.EUIDark]: mergePartial(DARK_THEME, EUI_CHARTS_THEME_DARK.theme, { mergeOptionalPartialValues: true }),
 };
 
-const getBackground = (colorId: string) => {
-  const option = (storybookParameters?.background?.options ?? []).find(({ id }) => id === colorId);
-  return option?.background ?? option?.color ?? '#fff';
-};
-
```
Comment (nickofthyme) [inline storybook/use_base_theme.ts:48]: Why are you removing this? The background fro the context is the `id` of the option and not necessarily the color.

Comment (markov00) [reply storybook/use_base_theme.ts:48]: not for the VRTs. If you check `useGlobalsParameters()` you already return `backgroundColor` that is a color then passed to the `BackgroundProvider` 

```tsx
const {
    themeName,
    backgroundColor,
    setParams,
  } = useGlobalsParameters();
  
  ....
  return (
    <ThemeProvider value={themeName as any}>
      <BackgroundProvider value={backgroundColor}>
        <Suspense fallback={<div>Loading...</div>}>
``` 

So probably we can change the `useGlobalsParameters` to compute and return the backgroundId instead of the backgroundColor

Comment (nickofthyme) [reply storybook/use_base_theme.ts:48]: resolved over zoom

**Review by nickofthyme — APPROVED** [review]
Code changes LGTM
