### PR TITLE
fix(reactive_chart): fix order of instantiation of onBruchEnd callback

### LINKED ISSUE #360: onBrushEnd should be called after setState is completed
**Describe the bug**
If onBrushEnd is given, it should call it after `setState` is completed, otherwise it occurs warnings about setting state when unmount.

For example, this is the function I am passing to `onBrushEnd`:

```
(min: number, max: number) => {
  setTimeout(() => {
    setAbsoluteRangeDatePicker({ id: 'global', from: min, to: max });
  }, 500);
}
```
The reason why I'm waiting for 500ms here is to make sure `setState is completed`.
https://github.com/elastic/elastic-charts/blob/master/src/components/react_canvas/reactive_chart.tsx#L305

**Expected behavior**
onBrushEnd should be called `after` setState is completed

**Screenshots**
If I remove `setTimeout`:

onBrushEnd

**Errors in browser console**
```
backend.js:1 Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in ReactiveChart
    in inject-ReactiveChart-with-chartStore
    in div
    in ChartContainer
    in inject-ChartContainer-with-chartStore
    in div
    in div
    in Provider
    in Chart
    in div
    in Unknown
    in Unknown (created by AutoSizer)
    in div (created by WrappedByAutoSizer)
    in WrappedByAutoSizer (created by AutoSizer)
    in AutoSizer
    in Unknown
    in div (created by EuiFlexItem)
    in EuiFlexItem (created by FlexItem)
    in FlexItem
    in div (created by EuiFlexGroup)
    in EuiFlexGroup
    in div (created by EuiPanel)
    in EuiPanel
    in div (created by EuiFlexItem)
    in EuiFlexItem (created by FlexItem)
    in FlexItem
    in Unknown
    in div (created by EuiFlexGroup)
    in EuiFlexGroup
```

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues here.

**Checklist**
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

### PR DESCRIPTION
**Pull request by nickofthyme**
## Summary

This PR fixes an issue found in SIEM where the `onBrushEnd` callback triggers a URL change and thus a rerender of the page and `Chart` components on the page. The workaround solution was to add a `500ms` `setTimeout` to allow time for the state to update before calling the `onBrushEnd` callback.

The solution as suggested by @FrankHassanabad, is to invoke the `onBrushEnd` callback following the completion of the `setState` method.

fixes #360

## Screenshot
Notice no console errors when brushing chart and successful update of time range and chart.
Screen Recording 2019-09-12 at 09 45 PM

Additionally, added `componentWillUnmount` method to ensure `window.removeEventListener` is called on `mouseup` event in the case where the `Chart` is unmounted before this event is called.
    
### Checklist

- [x] This was checked for cross-browser compatibility, [including a check against IE11](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#cross-browser-compatibility)
- [x] Each commit follows the [convention](https://github.com/elastic/elastic-charts/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/components/react_canvas/reactive_chart.tsx [hunk 1]
```diff
@@ -76,6 +76,10 @@ class Chart extends React.Component<ReactiveChartProps, ReactiveChartState> {
     },
   };
 
+  componentWillUnmount() {
+    window.removeEventListener('mouseup', this.onEndBrushing);
+  }
```
Comment (markov00) [inline src/components/react_canvas/reactive_chart.tsx]: ❤️
