### PR TITLE
fix(domain): set domain bounds dependent on negative/positive values

### LINKED ISSUE #135: The chart do not render negative values
**Describe the bug**
The chart do not render negative values (y-axis). But the tooltip still show these values.

To check this behavior in TSVB you could use `bucket_script` option:
image

The tooltip still renders negative values:
negative_values

Here is the series data: 
```
[[1554066000000,-2],[1554066600000,-1],[1554067200000,null],[1554067800000,-1],[1554068400000,-1],[1554069000000,-1],[1554069600000,-2],[1554070200000,-2],[1554070800000,-4],[1554071400000,-3],[1554072000000,null],[1554072600000,-3],[1554073200000,-3],[1554073800000,-2],[1554074400000,-7],[1554075000000,-5],[1554075600000,-6],[1554076200000,-6],[1554076800000,-5],[1554077400000,-7],[1554078000000,-4],[1554078600000,-8],[1554079200000,-10],[1554079800000,-5],[1554080400000,-10],[1554081000000,-6],[1554081600000,-10],[1554082200000,-6],[1554082800000,null],[1554083400000,-10],[1554084000000,-14],[1554084600000,-14],[1554085200000,-17],[1554085800000,-12],[1554086400000,-21],[1554087000000,-20],[1554087600000,-18],[1554088200000,-29],[1554088800000,-25],[1554089400000,-25],[1554090000000,-35],[1554090600000,-37],[1554091200000,-25],[1554091800000,-32],[1554092400000,-37],[1554093000000,-43],[1554093600000,-48],[1554094200000,-51],[1554094800000,-38],[1554095400000,-50],[1554096000000,-56],[1554096600000,-60],[1554097200000,-54],[1554097800000,-51],[1554098400000,-71],[1554099000000,-62],[1554099600000,-73],[1554100200000,-73],[1554100800000,-62],[1554101400000,-69],[1554102000000,-75],[1554102600000,-67],[1554103200000,-78],[1554103800000,-70],[1554104400000,-77],[1554105000000,-94],[1554105600000,-86],[1554106200000,-80],[1554106800000,-82],[1554107400000,-97],[1554108000000,-91],[1554108600000,-86],[1554109200000,-83],[1554109800000,-76],[1554110400000,-105],[1554111000000,-80],[1554111600000,-77],[1554112200000,-87],[1554112800000,-81],[1554113400000,-86],[1554114000000,-90],[1554114600000,-75],[1554115200000,-69],[1554115800000,-55],[1554116400000,-71],[1554117000000,-57],[1554117600000,-65],[1554118200000,-71],[1554118800000,-86],[1554119400000,-70],[1554120000000,-66],[1554120600000,-65],[1554121200000,-52],[1554121800000,-55],[1554122400000,-60],[1554123000000,-45],[1554123600000,-53],[1554124200000,-37],[1554124800000,-42],[1554125400000,-35],[1554126000000,-39],[1554126600000,-40],[1554127200000,-43],[1554127800000,-30],[1554128400000,-15],[1554129000000,-19],[1554129600000,-28],[1554130200000,-21],[1554130800000,-17],[1554131400000,-15],[1554132000000,-18],[1554132600000,-15],[1554133200000,-14],[1554133800000,-10],[1554134400000,-9],[1554135000000,null],[1554135600000,-4],[1554136200000,-10],[1554136800000,-12],[1554137400000,-12],[1554138000000,-8],[1554138600000,-12],[1554139200000,-6],[1554139800000,-3],[1554140400000,-9],[1554141000000,-5],[1554141600000,-2],[1554142200000,-6],[1554142800000,-3],[1554143400000,-1],[1554144000000,-1],[1554144600000,-1],[1554145200000,null],[1554145800000,null],[1554146400000,-2],[1554147000000,-2],[1554147600000,null],[1554148200000,-1],[1554148800000,-1],[1554149400000,null],[1554150000000,null],[1554150600000,-2],[1554151200000,null]]
```

**To Reproduce**
1. Create a chart with negative y-axis values
2. The chart do not render them
3. Hover on a chart -> tooltip shows negative values

**Expected behavior**
The chart should be rendered properly

**Version (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 73
 - Elastic Charts: 3.4.4

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues here.

**Checklist**
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

### PR DESCRIPTION
**Pull request by emmacunningham**
## Summary

close #135

This PR addresses the issues with the previous `scaleToExtent` logic assuming a domain with only positive values.  Now, when `scaleToExtent` is false, we return a domain dependent on whether the domain has positive or negative values.  Previously, a chart with only negative values would only see the values rendering if `scaleToExtent` was true; now even when `scaleToExtent` is false, the negative values will render.  For mixed negative & positive values, we return the original domain.

scale_to_extent

### Checklist

Use ~~strikethroughs~~ to remove checklist items you don't feel are applicable to this PR.

- [x] This was checked for cross-browser compatibility, [including a check against IE11](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#cross-browser-compatibility)
- [x] Proper documentation or storybook story was added for features that require explanation or tutorials
- [x] Unit tests were updated or added to match the most common scenarios
- [x] Each commit follows the [convention](https://github.com/elastic/elastic-charts/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/lib/utils/domain.ts [hunk 1]
```diff
@@ -40,18 +40,37 @@ export function computeOrdinalDataDomain(
...
+    if (start >= 0 && end >= 0) {
+      return scaleToExtent ? [start, end] : [0, end];
+    } else if (start < 0 && end < 0) {
+      return scaleToExtent ? [start, end] : [start, 0];
+    }
+    return [start, end];
+  }
+
+  // if any of the values are null
+  return [0, 0];
```
Comment (emmacunningham) [inline src/lib/utils/domain.ts]: `d3.extent()` has the type signature `[number, number] | [undefined, undefined]`, so there's a possibility that the computed range start and end could be `undefined`, though consumers of this function appear to operate under the assumption that this is always `[number, number]`.

This seems like a case where if any value within the computed extent is `undefined`, we should handle it as an error and surface it to the user somehow (see #117).  The other option is that we coerce the `undefined`s:

```
[ -start, undefined ] => [ -start, 0 ]
[ +start, undefined ] => [ 0, start ] ?
[ undefined, -end ] => [ end, 0 ] ?
[ undefined, +end ] => [ 0, end ]
[ undefined, undefined ] => [0, 0]
```

Comment (markov00) [reply src/lib/utils/domain.ts]: I agree
