### PR TITLE
fix(specs):add custom style inside each specific series style

### LINKED ISSUE #188: The custom styling props should be series specific
**Describe the bug**
The current implementation of `BasicSeriesSpec` incorporate the custom styles for each different series.
```
export type BasicSeriesSpec = SeriesSpec & SeriesAccessors & SeriesScales & {
  barSeriesStyle?: CustomBarSeriesStyle;
  lineSeriesStyle?: LineSeriesStyle;
  areaSeriesStyle?: AreaSeriesStyle;
};
```

**Expected behavior**
Each custom style should be declared inside it's specific series style like

```
export type BarSeriesSpec = BasicSeriesSpec & {
  /** @default bar */
  seriesType: 'bar';
  barSeriesStyle?: CustomBarSeriesStyle;
};

export type LineSeriesSpec = BasicSeriesSpec & {
  /** @default line */
  seriesType: 'line';
  curve?: CurveType;
  lineSeriesStyle?: LineSeriesStyle;
};
```

### PR DESCRIPTION
**Pull request by rshen91**
## Summary

Fixes #188 
In specs.ts, BasicSeriesSpec included the styles for LineSeriesSpec, AreaSeriesSpec, and BarSeriesSpec. This PR removes barSeriesStyle, lineSeriesStyle, and areaSeriesStyle from BasicSeries style and includes the SeriesStyle per each chart type. 

Included in specs.ts are the type guards for utils.ts 

```
export function isBarSeriesSpec(spec: BasicSeriesSpec): spec is BarSeriesSpec {
  return spec.seriesType === 'bar';
}

export function isLineSeriesSpec(spec: BasicSeriesSpec): spec is LineSeriesSpec {
  return spec.seriesType === 'line';
}

export function isAreaSeriesSpec(spec: BasicSeriesSpec): spec is AreaSeriesSpec {
  return spec.seriesType === 'area';
}
```

### Checklist

~~-  Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)~~
~~-  Proper documentation or storybook story was added for features that require explanation or tutorials~~

~~- [ ] This was checked for cross-browser compatibility, [including a check against IE11](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#cross-browser-compatibility)~~

~~- [ ] Unit tests were updated or added to match the most common scenarios~~
- [X] Each commit follows the [convention](https://github.com/elastic/elastic-charts/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/lib/series/specs.ts [hunk 1]
```diff
@@ -141,6 +143,7 @@ export type AreaSeriesSpec = BasicSeriesSpec & {
   seriesType: 'area';
   /** The type of interpolator to be used to interpolate values between points */
   curve?: CurveType;
+  areaSeriesStyle?: AreaSeriesStyle;
 };
```
Comment (emmacunningham) [inline src/lib/series/specs.ts]: These should also be removed from BasicSeriesSpec so that they are defined only for the specific spec type.

Comment (rshen91) [reply src/lib/series/specs.ts]: Ah! Following - added commit ef1bbfd

File: src/lib/series/specs.ts [hunk 2]
```diff
@@ -110,39 +110,41 @@ export interface SeriesScales {
...
+export type  AreaSeriesSpec = SeriesSpec &  {
   /** @default area */
   seriesType: 'area';
   /** The type of interpolator to be used to interpolate values between points */
   curve?: CurveType;
+  areaSeriesStyle?: AreaSeriesStyle;
 };
 
+// export a joined type what series spec are available by different fnctions
+export type AnySeriesSpec = BarSeriesSpec | LineSeriesSpec | AreaSeriesSpec;
```
Comment (emmacunningham) [inline src/lib/series/specs.ts]: We want to avoid doing this.  The purpose of this fix is to make each custom series style specific only to the relevant series spec.

File: src/lib/series/rendering.areas.test.ts [hunk 3]
```diff
@@ -4,13 +4,13 @@ import { ScaleType } from '../utils/scales/scales';
...
 import { computeXScale, computeYScales } from './scales';
-import { AreaSeriesSpec } from './specs';
+import { AreaSeriesSpec, BasicSeriesSpec } from './specs';
 const SPEC_ID = getSpecId('spec_1');
 const GROUP_ID = getGroupId('group_1');
 
 describe('Rendering points - areas', () => {
   describe('Single series area chart - ordinal', () => {
-    const pointSeriesSpec: AreaSeriesSpec = {
+    const pointSeriesSpec: AreaSeriesSpec | BasicSeriesSpec = {
```
Comment (emmacunningham) [inline src/lib/series/rendering.areas.test.ts]: Here and other places where you're casting the type as either the specific series type or the basic series: 

We should keep the casted type to just the specific series.

File: src/state/utils.ts [hunk 4]
```diff
@@ -440,7 +441,7 @@ export function renderGeometries(
   };
 }
 
-export function getSpecById(seriesSpecs: Map<SpecId, BasicSeriesSpec>, specId: SpecId) {
+export function getSpecById(seriesSpecs: Map<SpecId, BasicSeriesSpec & AnySeriesSpec>, specId: SpecId) {
```
Comment (emmacunningham) [inline src/state/utils.ts]: Per my comment earlier, we don't want to introduce this additional type.

I think you've introduced this to get around the issues where the specific series styles are not defined on the BasicSeriesSpec (expected once we remove them), but this is not the way to go about resolving that problem as this introduce an additional generic type and more complications to the type system.  Instead we want to leave the specific style properties specific to the relevant spec type, that is:

```
export type BasicSeriesSpec = SeriesSpec & SeriesAccessors & SeriesScales;

/**
 * This spec describe the dataset configuration used to display a bar series.
 */
export type BarSeriesSpec = BasicSeriesSpec & {
  /** @default bar */
  seriesType: 'bar';
  barSeriesStyle?: CustomBarSeriesStyle;
};

/**
 * This spec describe the dataset configuration used to display a line series.
 */
export type LineSeriesSpec = BasicSeriesSpec & {
  /** @default line */
  seriesType: 'line';
  curve?: CurveType;
  lineSeriesStyle?: LineSeriesStyle;
};

/**
 * This spec describe the dataset configuration used to display an area series.
 */
export type AreaSeriesSpec = BasicSeriesSpec & {
  /** @default area */
  seriesType: 'area';
  /** The type of interpolator to be used to interpolate values between points */
  curve?: CurveType;
  areaSeriesStyle?: AreaSeriesStyle;
};
```

Then, in `renderGeometries` in `utils`, you'll need to correct the type errors by casting each series spec to the more specific type (they come in as `BasicSeriesSpec`s but once we know what the `seriesType` is, we can reliably cast them to the more specific types).

The quick fix is to just cast them inline; in `renderGeometries` there's the switch statement on `spec.seriesType`, to cast, say, the line spec, you could do:

```
case 'line': 
  const lineSpec = spec as LineSeriesSpec;
  const lineSeriesStyle = lineSpec.lineSeriesStyle; // This will now be defined because lineSpec has been cast as a LineSeriesSpec which does have this property unlike BasicSeriesSpec which doesnt
```

A slightly more elegant way to handle this which doesn't require that you explicitly cast within the `renderGeometries` function would be to use a type guard (you'd also then swap out the `switch/case` for an `if/else`) [see the user defined type guards section [here](https://www.typescriptlang.org/docs/handbook/advanced-types.html); there are also examples of this for the AnnotationSpec types and the way that the differently bounded domain types in `axis_utils` are handled]

Comment (markov00) [reply src/state/utils.ts]: Another suggestion, instead of casting the spec to a specific type with `spec as LineSeriesSpec;` you can change the `switch` to a series of if and add few utilities functions that helps TS identify your general type like:
```
function isLineSeriesSpec(spec: BasicSeriesSpec): spec is LineSeriesSpec {
    return spec.seriesType === 'line';
}
```
This will also helps in case we want to change the seriesType value in the future or the BasicSeriesSpec in general, we can just change the helper functions and not all places where we are testing `seriesType` attribute to find the specific type.

Comment (rshen91) [reply src/state/utils.ts]: Awesome! - addressed in commit a1f62ec

File: src/lib/series/rendering.areas.test.ts (hunk 3 above)
Comment (rshen91) [reply src/lib/series/rendering.areas.test.ts]: I reverted a few commits and then squashed them in 8c9653d

File: src/lib/series/specs.ts (hunk 2 above)
Comment (rshen91) [reply src/lib/series/specs.ts]: I reverted a couple commits and then squashed them in 8c9653d
