### PR TITLE
fix(chart_state): maintain series visibility state on props update

### LINKED ISSUE #113: Series visibility state is lost when a chart props changed
**Describe the bug**

The visibility state of a series is lost when sending updated props to a chart

image

It is also reproducible in the [storybook](https://elastic.github.io/elastic-charts/?selectedKind=Stylings&selectedStory=margins%20and%20paddings&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs)

series_visibility_issue

**To Reproduce**
1. Press the eye button on a series -> the series should become invisible
2. Change any prop in `KNOBS` tab
3. the series become visible again

**Expected behavior**
The visibility of the series should stay in that state until press the button again or the chart  unmount.

**Screenshots**
It becomes useless in kibana TSVB because it updates on every click:

series_visibility_issue_in_tsvb

**Version (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 73
 - Elastic Charts: 3.2.0

**Errors in browser console**
-

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues here.

**Checklist**
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

### PR DESCRIPTION
**Pull request by emmacunningham**
## Summary

fix #113 

This PR fixes the issue where the visibility of the data series would reset on every state change.

Previously, `resetSelectedDataSeries` was being called in `componentDidUpdate` on `SpecsParser`.  Instead of keeping track of `selectedDataSeries` (and assuming `isVisible: false` as the default), we now assume visibility as the default and keep track of `deselectedDataSeries`.  This has the advantage that we do not need to reset any kind of visibility and visibility state can be better preserved as specs are being updated & added.

- splitAccessors change
visibility_split_change

- yAccessors change
visibility_y_change

- changes in split accessor values in data
visibility_data_change

- removing a series that is the only selected visible series (this is the same as the functionality in current kibana)
visibility_remove_data

### Checklist

Use ~~strikethroughs~~ to remove checklist items you don't feel are applicable to this PR.

- [x] This was checked for cross-browser compatibility, [including a check against IE11](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#cross-browser-compatibility)
- [x] Proper documentation or storybook story was added for features that require explanation or tutorials
- [x] Unit tests were updated or added to match the most common scenarios
- [x] Each commit follows the [convention](https://github.com/elastic/elastic-charts/blob/master/CONTRIBUTING.md)

### CODE REVIEW

File: src/state/utils.ts [hunk 1]
```diff
@@ -63,6 +64,30 @@ export function findSelectedDataSeries(
...
+  prevSeriesColors: Map<string, DataSeriesColorsValues>,
+  prevSeriesSpecs: Map<SpecId, BasicSeriesSpec>,
+  prevSelectedDataSeries: DataSeriesColorsValues[] | null,
+  nextSeriesSpec: BasicSeriesSpec | LineSeriesSpec | AreaSeriesSpec | BarSeriesSpec,
+
+): boolean {
+  const nextSeriesSpecs = new Map([...prevSeriesSpecs]);
+  nextSeriesSpecs.set(nextSeriesSpec.id, nextSeriesSpec);
+
+  const nextSeriesColors = getSplittedSeries(nextSeriesSpecs, prevSelectedDataSeries).seriesColors;
```
Comment (markov00) [inline src/state/utils.ts]: using `getSplittedSeries` is quite expensive, specially on charts with an high number of elements/series.
It's an  heavy function because it internally use `splitSeries` that cycle all the datums for each series and all the x values after that.
Can't we find a better way to detect that change? checking only if we are adding a new spec or if it's already there and differ from the existing one. 
In case you can create a test case to to check if that decrease or not the performance when having 200 data points with 20/30 series (that doesn't mean to have a readable chart but we can stress test it a bit)

Comment (emmacunningham) [reply src/state/utils.ts]: Instead of storing the selected (visible) data series, we store the deselected data series.  This removes the need to reset in response to certain conditions because by default all series will be visible and we only keep track of what is deselected (not visible).  This also better preserves visibility state when making changes to the spec.

File: stories/interactions.tsx [hunk 2]
```diff
@@ -177,9 +177,57 @@ storiesOf('Interactions', module)
...
+      min: number('yDomain min', 0, {}, notSpecChange),
+      max: number('yDomain max', 10, {}, notSpecChange),
+    };
+
+    const scaleTypeOptions: { [key: string]: ScaleType.Linear | ScaleType.Log } = {
+      linear: ScaleType.Linear,
+      log: ScaleType.Log,
+    };
+
+    const xScaleType = select('xScaleType', scaleTypeOptions, ScaleType.Linear, specChange);
```
Comment (markov00) [inline stories/interactions.tsx]: I think we have a bug and we allow also log scale for x scale, that's not actually possible.
could you please correct this on the story, we can open a PR for fixing this on the props.

Comment (emmacunningham) [reply stories/interactions.tsx]: 👍 For xDomain it should only be Time, Linear, and Ordinal, right?

Comment (markov00) [reply stories/interactions.tsx]: yep

Comment (emmacunningham) [reply stories/interactions.tsx]: Removed the option to change xScaleType on this story (it doesn't really make sense to switch it for an ordinal or time scale type with this dataset and the point that changing scale types doesn't change the visibility state is already demonstrated by yScaleType changes) in this commit https://github.com/elastic/elastic-charts/pull/118/commits/fe7b307a01224210aee7e7011cf68ce14dc12d29

Created issue #122 to address the bug.
