### PR TITLE
fix: line path with ordered xValues

### LINKED ISSUE #680: Missing values default to value when stacked
**Describe the bug**
When a value is missing from a given series, the value is correctly skipped when the series is not stacked. But when the values are stacked the charts fills in a value.

See https://codesandbox.io/s/confident-https-gwrks?file=/src/App.tsx

**Expected behavior**
Should skip the value and not loop back.

**Screenshots**
image

> Area opacity set to zero for clarity

### LINKED ISSUE #823: Order values by sum causes bad line path
**Describe the bug**
Using `orderOrdinalBinsBy` draws line out of order.

**To Reproduce**
1. Go to https://elastic.github.io/elastic-charts/?path=/story/bar-chart--order-bins-by-sum
2. Change `BarSeries` to `LineSeries`
3. Ensure `orderOrdinalBinsBy` in enabled
4. Notice the line is drawn out of order

**Expected behaviour**
Draws line in sequential order with `orderOrdinalBinsBy` setting enabled.

**Screenshots**
Screen Recording 2020-09-15 at 10 24 AM

### PR DESCRIPTION
**Pull request by nickofthyme**
## Summary

fixes #823 
re-fixes #680

Fix line path with ordered `xValues` on `Ordinal` scales.

### Before
Image 2020-09-15 at 4 00 59 PM

### After
image

### Checklist

- [x] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [x] This was checked for cross-browser compatibility
- [x] Proper documentation or storybook story was added for features that require explanation or tutorials
- [x] Unit tests were updated or added to match the most common scenarios

### CODE REVIEW

File: stories/line/10_test_path_ordering.tsx [hunk 1]
```diff
@@ -0,0 +1,81 @@
...
+      <LineSeries
+        id="bars1"
+        fit="linear"
+        xScaleType={ScaleType.Ordinal}
+        yScaleType={ScaleType.Linear}
+        xAccessor="x"
+        yAccessors={['y1', 'y2']}
+        splitSeriesAccessors={['g']}
+        stackAccessors={boolean('Stacked', true) ? ['g'] : undefined}
+        data={data}
```
Comment (markov00) [inline stories/line/10_test_path_ordering.tsx:70]:
```suggestion
        data={orderOrdinalBinsBy  ? _.shuffle(data) : data}
```
so we can test every possible sorting order

**Review by markov00 — APPROVED** [review]
Tested locally, works great
I've added a small comment to improve the testing
