### PR TITLE
fix(annotations): provide fallback for line annotation markers

### LINKED ISSUE #1036: Wrong annotation marker position without axis
**Describe the bug**
When adding an X line annotation in a chart without the relative X `<Axis>` component, the marker position is not correctly computed and placed offscreen

**To Reproduce**
1. Go to https://codesandbox.io/s/holy-fog-6x90l?file=/src/App.tsx
2. See the annotation on the middle-left of the screen (barely visible)

**Expected behavior**
The annotation marker should be placed on a default position for the X or Y domain

**Screenshots**
Screenshot 2021-02-18 at 19 32 31
image (3)

**Version (please complete the following information):**
 - OS: all
 - Browser: all
 - Elastic Charts: 25.x

**Additional context**
Discovered by ML team.

Current workaround: manually specify the `markerPosition` prop on the `LineAnnotation`

**Errors in browser console**
N/A

**Kibana Cross Issues**
- https://github.com/elastic/kibana/pull/91899

### PR DESCRIPTION
**Pull request by rshen91**
## Summary
Fixes #1036 
In the playground, if there is no `SpecMarkerPosition` this doesn't seem to lead to the same sort of bug where the marker is off the chart. 

Added a story under test cases and test stories with rotations.

### CODE REVIEW

File: src/chart_types/xy_chart/annotations/line/dimensions.ts [hunk 1]
```diff
@@ -283,8 +283,12 @@ function getAnchorPosition(
   isXDomain: boolean,
   isChartHorizontal: boolean,
   specMarkerPosition?: Position,
-  axisPosition?: Position,
+  axisPosition?: Position | undefined,
 ): Position {
+  // catch the case of a chart with no axes nor specMarkerPosition for a vertical line annotation
+  if (!axisPosition && !specMarkerPosition && isXDomain) {
+    return Position.Bottom;
+  }
```
Comment (markov00) [inline src/chart_types/xy_chart/annotations/line/dimensions.ts:291]: Can you please check the `getDefaultMarkerPositionFromAxis` function? I see that this also covers the case there the `axisPosition` is `undefined` but I don't know if we are considering all the cases.

Comment (rshen91) [reply src/chart_types/xy_chart/annotations/line/dimensions.ts]: Thank you! 2b4f5de

File: src/chart_types/xy_chart/annotations/line/dimensions.ts [hunk 2]
```diff
@@ -310,7 +309,7 @@ function getDefaultMarkerPositionFromAxis(
   if (axisPosition) {
     return axisPosition;
   }
-  if ((isXDomain && isHorizontal) || (!isXDomain && !isHorizontal)) {
+  if (!isXDomain && isHorizontal) {
```
Comment (markov00) [inline src/chart_types/xy_chart/annotations/line/dimensions.ts:312]: This doesn't covers all the cases. Please check and fix this to cover the case where the chart is rotated 90,-90 degrees.

File: src/chart_types/xy_chart/annotations/line/dimensions.ts [hunk 3]
```diff
@@ -283,10 +283,9 @@ function getAnchorPosition(
   isXDomain: boolean,
   isChartHorizontal: boolean,
   specMarkerPosition?: Position,
-  axisPosition?: Position,
+  axisPosition?: Position | undefined,
```
Comment (markov00) [inline src/chart_types/xy_chart/annotations/line/dimensions.ts:286]: this argument is already optional when using the `?`

File: src/chart_types/xy_chart/annotations/line/dimensions.ts [hunk 4]
```diff
@@ -297,7 +296,7 @@ function getAnchorPosition(
 
 function validateMarkerPosition(isXDomain: boolean, isHorizontal: boolean, position: Position): Position | undefined {
   if ((isXDomain && isHorizontal) || (!isXDomain && !isHorizontal)) {
-    return position === Position.Top || position === Position.Bottom ? position : undefined;
+    return position === Position.Top || position === Position.Bottom ? position : Position.Bottom;
```
Comment (markov00) [inline src/chart_types/xy_chart/annotations/line/dimensions.ts:299]: this defaults to the `dflPositionFromAxis` if the configured `specMarkerPosition` doesn't pass this validation.
It's better to keep the defaults in a single place

**Review by markov00 — COMMENTED** [review]
Left few comments: in particular, it needs to account for rotations.
Can you also please add a specific VRT that changes the rotation and checks the 4 rotations values screenshots?

**Comment by rshen91** [comment]
I was facing an issue in three stories (http://localhost:9001/?path=/story/bar-chart--functional-accessors, http://localhost:9001/?path=/story/annotations-rects--linear-bar-chart and https://elastic.github.io/elastic-charts/?path=/story/annotations-rects--ordinal-bar-chart) that were solved by this fix: https://github.com/storybookjs/storybook/issues/6981#issuecomment-502140984 seen in commit e58089a

File: src/chart_types/xy_chart/annotations/line/dimensions.ts (hunk 2 above)
Comment (rshen91) [reply src/chart_types/xy_chart/annotations/line/dimensions.ts]: Thank you! Please see changes in e58089a 🙇‍♀️

File: src/chart_types/xy_chart/annotations/line/dimensions.ts (hunk 3 above)
Comment (rshen91) [reply src/chart_types/xy_chart/annotations/line/dimensions.ts]: changed in e58089a thank you!

**Comment by rshen91** [comment]
jenkins test this

File: integration/tests/test_cases_stories.test.ts [hunk 5]
```diff
@@ -36,4 +36,28 @@ describe('Test cases stories', () => {
...
+    await common.expectChartAtUrlToMatchScreenshot(
+      'http://localhost:9001/iframe.html?id=test-cases--no-axes-annotation-bug-fix&knob-horizontal marker position=undefined&knob-vertical marker position=undefined&knob-chartRotation=-90',
+    );
+  });
+
+  it('should render marker with annotations with 180 deg rotation', async () => {
+    await common.expectChartAtUrlToMatchScreenshot(
+      'http://localhost:9001/iframe.html?id=test-cases--no-axes-annotation-bug-fix&knob-horizontal marker position=undefined&knob-vertical marker position=undefined&knob-chartRotation=180',
+    );
+  });
```
Comment (markov00) [inline integration/tests/test_cases_stories.test.ts:62]: nit: you can use https://jestjs.io/docs/api#1-testeachtablename-fn-timeout instead of having 4 similar tests with just one parameter change.
Something like:
```
it.each([0,90, -90,180],'should render marker with annotations with %d deg rotations', () =>)
```

File: src/chart_types/xy_chart/annotations/line/dimensions.ts [hunk 6]
```diff
@@ -84,6 +83,14 @@ function computeYDomainLineAnnotationDimensions(
 
         const width = isHorizontalChartRotation ? horizontal.bandwidth : vertical.bandwidth;
         const height = isHorizontalChartRotation ? vertical.bandwidth : horizontal.bandwidth;
+        const linePathPoints = getYLinePath({ width, height }, annotationValueYPosition);
+        const alignment = getAnchorPosition(
+          false,
+          // isHorizontalChartRotation,
```
Comment (markov00) [inline src/chart_types/xy_chart/annotations/line/dimensions.ts:89]: you can remove this

File: src/chart_types/xy_chart/annotations/line/dimensions.ts [hunk 7]
```diff
@@ -197,6 +201,15 @@ function computeXDomainLineAnnotationDimensions(
         const width = isHorizontalChartRotation ? horizontal.bandwidth : vertical.bandwidth;
         const height = isHorizontalChartRotation ? vertical.bandwidth : horizontal.bandwidth;
 
+        const linePathPoints = getXLinePath({ width, height }, annotationValueXPosition);
+        const alignment = getAnchorPosition(
+          true,
+          // isHorizontalChartRotation,
```
Comment (markov00) [inline src/chart_types/xy_chart/annotations/line/dimensions.ts:207]: you can remove this

File: src/chart_types/xy_chart/annotations/line/dimensions.ts [hunk 8]
```diff
@@ -281,36 +292,41 @@ export function computeLineAnnotationDimensions(
...
   return dflPositionFromAxis;
 }
 
-function validateMarkerPosition(isXDomain: boolean, isHorizontal: boolean, position: Position): Position | undefined {
-  if ((isXDomain && isHorizontal) || (!isXDomain && !isHorizontal)) {
+function validateMarkerPosition(isXDomain: boolean, chartRotation: number, position: Position): Position | undefined {
+  if (
+    (isXDomain && (chartRotation === 0 || chartRotation === 180)) ||
+    (!isXDomain && (chartRotation === 90 || chartRotation === -90))
+  ) {
```
Comment (markov00) [inline src/chart_types/xy_chart/annotations/line/dimensions.ts:312]:
```suggestion
  if (
    (isXDomain && isHorizontalRotation(chartRotation)) ||
    (!isXDomain && isVerticalRotation(chartRotation))
  ) {
```

File: src/chart_types/xy_chart/annotations/line/dimensions.ts [hunk 9]
```diff
@@ -281,36 +292,41 @@ export function computeLineAnnotationDimensions(
...
+  chartRotation: number,
   axisPosition?: Position,
 ): Position {
   if (axisPosition) {
     return axisPosition;
   }
-  if ((isXDomain && isHorizontal) || (!isXDomain && !isHorizontal)) {
+  if (
+    (isXDomain && (chartRotation === 90 || chartRotation === -90)) ||
+    (!isXDomain && (chartRotation === 0 || chartRotation === 180))
```
Comment (markov00) [inline src/chart_types/xy_chart/annotations/line/dimensions.ts:328]: same as above

**Review by markov00 — COMMENTED** [review]
I haven't understood why we need to use that and what changed on master.
I've checked the currently deployed storybook and seems to work pretty well the text here.
Can you please run a rm -rf node_modules && yarn install to clean up the dependencies and checks if the problem persist without the marked dependency?

File: src/chart_types/xy_chart/annotations/line/dimensions.ts (hunk 9 above)
Comment (rshen91) [reply src/chart_types/xy_chart/annotations/line/dimensions.ts]: Thank you! 0ba5d9b

File: src/chart_types/xy_chart/annotations/line/dimensions.ts (hunk 8 above)
Comment (rshen91) [reply src/chart_types/xy_chart/annotations/line/dimensions.ts]: Much cleaner thanks! 0ba5d9b

File: src/chart_types/xy_chart/annotations/line/dimensions.ts (hunk 7 above)
Comment (rshen91) [reply src/chart_types/xy_chart/annotations/line/dimensions.ts]: 👍 0ba5d9b

File: src/chart_types/xy_chart/annotations/line/dimensions.ts (hunk 6 above)
Comment (rshen91) [reply src/chart_types/xy_chart/annotations/line/dimensions.ts]: 👍 0ba5d9b

File: integration/tests/test_cases_stories.test.ts (hunk 5 above)
Comment (rshen91) [reply integration/tests/test_cases_stories.test.ts]: I did something similar, thanks - 0ba5d9b

**Comment by rshen91** [comment]
> I haven't understood why we need to use that and what changed on master.
> I've checked the currently deployed storybook and seems to work pretty well the text here.
> Can you please run a rm -rf node_modules && yarn install to clean up the dependencies and checks if the problem persist without the marked dependency?

You were right! Thanks! 0ba5d9b

**Review by markov00 — APPROVED** [review]
All good for me! thanks for the changes
