### PR TITLE
fix(heatmap): filter out tooltip picked shapes in x-axis area

### LINKED ISSUE #1215: Paginated heatmap shows tooltip outside the projection area
**Describe the bug**
A heatmap can be paginated: depending on the cell/grid configuration is possible to reduce the number of rows shown to fit into the screen. 
We track the mouse position outside the projection area. The geometry picking logic doesn't exclude the non-rendered cells causing the tooltip to appear when hovering near the axis but outside the projection area.

 

**To Reproduce**
1. Go to https://elastic.github.io/elastic-charts/?path=/story/heatmap-alpha--categorical
2. move the mouse near the bottom part of the chart, over the x axis
3. the tooltip, related to non-visible cells will appear 

**Expected behaviour**
The tooltip should only be active for the visible cells

**Screenshots**
Jun-22-2021 19-54-38

**Version (please complete the following information):**
 - Elastic Charts: 30.x

**Additional context**
n/a

**Errors in browser console**
n/a

### PR DESCRIPTION
**Pull request by rshen91**
## Summary

This bug fix removes the tooltip when hovering over the x-axis. 

### Before

https://user-images.githubusercontent.com/20343860/131744782-b8ec9192-d36e-4d36-bd3c-652741ec77e6.mp4

### After

https://user-images.githubusercontent.com/20343860/131744852-35e31147-40e2-4d2e-952f-a8a8cae9cfd2.mp4

## Details
- [x] Adjust cursor logic 

## Issues
Closes #1215 

### Checklist

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] All related issues have been linked (i.e. `closes #123`, `fixes #123`)

### CODE REVIEW

**Review by markov00 — COMMENTED** [review]
Logically looks correct, do you think we can apply this `pickedShapes` filter directly into the `getPickedShapes` selector to control and fix that in a single place?

**Comment by rshen91** [comment]
> Logically looks correct, do you think we can apply this `pickedShapes` filter directly into the `getPickedShapes` selector to control and fix that in a single place?

I'm definitely going to try -- the issue I'm facing is the return type of pickedShapes can be an array of Cells or TextBox so it's more complicated than I had hoped :)

**Comment by rshen91** [comment]
@markov00 in 8358dd8 I cleaned it up in the picked_shapes selector but I was struggling to find a cleaner way to deal with the cursor logic in get_cursor_pointer.ts (like a way to avoid the length check in get_cursor_pointer). I was trying to move that length check into picked_shapes but kept facing issues with typescript and returning boolean values. Is there a cleaner way I'm overlooking or is the refactoring in 8358dd8 ok? Thanks

**Comment by rshen91** [comment]
jenkins test this

File: packages/charts/src/chart_types/heatmap/state/selectors/picked_shapes.ts [hunk 1]
```diff
@@ -10,17 +10,21 @@ import { GlobalChartState } from '../../../../state/chart_state';
...
-  (geoms, pointerPosition): Cell[] | TextBox => {
+  [geometries, getCurrentPointerPosition, getGridHeightParamsSelector],
+  (geoms, pointerPosition, gridParams): Cell[] | TextBox => {
     const picker = geoms.pickQuads;
     const { x, y } = pointerPosition;
-    return picker(x, y);
+    const arrayPicker = picker(x, y) as Cell[];
+    return Array.isArray(picker(x, y))
+      ? arrayPicker.filter(({ y }) => y < gridParams.gridCellHeight * gridParams.pageSize)
+      : picker(x, y);
```
Comment (markov00) [inline packages/charts/src/chart_types/heatmap/state/selectors/picked_shapes.ts:28]: My suggestion is: 
- first of all call the `picker` function only one time
- don't cast it to `Cell[]` because it is not required in the code
- the ternary check `isArray` already allows TS and also JS to define if the pickedData is an array of Cell or a TextBox 
 

```suggestion
    const pickedData = picker(x, y);
    return Array.isArray(pickedData)
      ? pickedData.filter(({ y }) => y < gridParams.gridCellHeight * gridParams.pageSize)
      : pickedData;
```

**Comment by markov00** [comment]
Can you also please update the story with a knob that remove the filter on the BABY_NAME data so reviewers can test this easily without touching the code? thanks

File: packages/charts/src/chart_types/heatmap/state/selectors/picked_shapes.ts (hunk 1 above)
Comment (rshen91) [reply packages/charts/src/chart_types/heatmap/state/selectors/picked_shapes.ts]: Thank you! 6785db6 for changes and added the story changes into this commit as well

File: storybook/stories/heatmap/2_categorical.story.tsx [hunk 2]
```diff
@@ -15,7 +16,8 @@ import { BABYNAME_DATA } from '@elastic/charts/src/utils/data_samples/babynames'
 import { useBaseTheme } from '../../use_base_theme';
 
 export const Example = () => {
-  const data = BABYNAME_DATA.filter(([year]) => year > 1950 && year < 1960);
+  const filterData = boolean('filter BABYNAME_DATA', false);
+  const data = filterData ? BABYNAME_DATA : BABYNAME_DATA.filter(([year]) => year > 1950 && year < 1960);
```
Comment (markov00) [inline storybook/stories/heatmap/2_categorical.story.tsx:20]: Isn't that the inverse?
If I check the `filter` knob to enable the filter I should see only a partial set.
If the filter check is off, then I should see all the data available.
Two code change:
- reverse the ternary operation and change the default value of the checkbox to true
- rename the filter to: `filter dataset`. The BABYNAME_DATA is something we don't want to show to the user

**Review by markov00 — APPROVED** [review]
LGTM, good to merge after fixing the highlighted code change

File: storybook/stories/heatmap/2_categorical.story.tsx (hunk 2 above)
Comment (rshen91) [reply storybook/stories/heatmap/2_categorical.story.tsx]: Yikes good catch thanks 38147b4
