### PR TITLE
fix(heatmap): compute nice legend items from color scale 

### LINKED ISSUE #1166: Heatmap legend with linear color scale contains duplicate 0
**Describe the bug**
Heatmap chart with linear color scale ends up with duplicate `0` in legend items.

**To Reproduce**
Provide a dataset with values range from 0 to N.

**Expected behaviour**
Legend doesn't contain duplicate items.

**Screenshots**
image

**Kibana Cross Issues**
https://github.com/elastic/kibana/pull/97978

### LINKED ISSUE #1191: [Heatmap] Legend occasionally missing some entires
**Describe the bug**
Legend occasionally missing some value ranges from the chart data. 

**To Reproduce**
1. Set the `quantize` color scale 
2. Pass the chart data 
<details>
  <summary>Data payload</summary>

```
[
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "(empty)",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622152800000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 84
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "(empty)",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622239200000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 79
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "(empty)",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622325600000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 88
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "(empty)",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622412000000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 92
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "(empty)",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622498400000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 89
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "(empty)",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622584800000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 81
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "(empty)",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622671200000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 99
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "(empty)",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622757600000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 47
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "gz",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622152800000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 43
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "gz",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622239200000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 38
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "gz",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622325600000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 40
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "gz",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622412000000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 40
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "gz",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622498400000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 37
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "gz",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622584800000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 44
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "gz",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622671200000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 32
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "gz",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622757600000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 27
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "css",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622152800000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 31
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "css",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622239200000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 38
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "css",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622325600000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 37
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "css",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622412000000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 36
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "css",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622498400000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 40
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "css",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622584800000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 40
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "css",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622671200000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 35
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "css",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622757600000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 28
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "__other__",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622152800000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 72
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "__other__",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622239200000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 75
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "__other__",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622325600000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 65
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "__other__",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622412000000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 63
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "__other__",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622498400000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 63
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "__other__",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622584800000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 66
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "__other__",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622671200000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 64
    },
    {
        "e3960daf-4dd6-4bee-ad35-33531fbb50b3": "__other__",
        "afd8f801-ec04-446c-b69b-f0c4dd182bf7": 1622757600000,
        "82a12112-07d1-4f40-9d09-cc60d8d379ac": 30
    }
]
```
</details>

**Expected behaviour**
Legend reflects the entire range of presented entries. 

**Screenshots**
image

### LINKED ISSUE #1192: [Heatmap] Using legend to hide items does not hide every element
The heatmap legend is not hiding _all_ of the values, which is [related to not all values being shown](https://github.com/elastic/elastic-charts/issues/1191) but a different issue. The main difference is that there are values which are appearing in the legend, but which are not being hidden properly:

In this screenshot I've hidden every item in the legend, which ranges from -10 to 50. Even with every value hidden, I am still seeing:

* 0 and 10
* -13, -11, and -16 (not shown in legend)

Screen Shot 2021-06-04 at 11 24 23 AM

### PR DESCRIPTION
**Pull request by markov00**
## Summary
The heatmap legend now correctly shows all the colors and values associated with the chosen scale, without duplicates and with all the available color bands computed.

## Details

The previous legend implementation lacks various details: the legend ticks provided by d3 are not always what we want on the legend and the relationship between colors and ticks wasn't perfect. The code now takes in consideration the various scale types characteristics applying the [missing values](https://github.com/elastic/elastic-charts/issues/1191) to renders correctly the legend items without [duplicates](https://github.com/elastic/elastic-charts/issues/1166).

With the changes, we also fixed the ability to hide all the cells from the legend as highlighted in the bug #1192 
## Issues

fix #1166
fix #1191 
fix #1192

### Checklist

- [x] The proper chart type label was added (e.g. :xy, :partition) if the PR involves a specific chart type
- [x] The proper feature label was added (e.g. :interactions, :axis) if the PR involves a specific chart feature
- [x] Whenever possible, please check if the closing issue is connected to a running GH project
- [x] Proper documentation or storybook story was added for features that require explanation or tutorials
- [x] Unit tests were updated or added to match the most common scenarios

### CODE REVIEW

**Comment by monfera** [comment]
Great improvement 🎉 

Wondering if a future PR could arrange the belonging color ramps vertically, it'd be easier to distinguish like colors (within shades of blue etc) vertically, than with the large horizontal jumps.

Also, I wonder about the greater than vs greater than or equal here, also apparently the same color, is it intended?

image

Eyeballing some other mock, it's just tests but yellow is something to avoid in production code as a color legend on a white background, right?

**Comment by monfera** [comment]
Also, again it's just a mock but it's something that people reference: would be great to avoid the inaccessible  red/green color pairing, eg. using red/blue or some such

File: packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts [hunk 1]
```diff
@@ -393,9 +393,9 @@ function getCellKey(x: NonNullable<PrimitiveValue>, y: NonNullable<PrimitiveValu
...
 function isFilteredValue(filterRanges: Array<[number, number | null]>, value: number) {
   return filterRanges.some(([min, max]) => {
-    if (max !== null && value > min && value < max) {
+    if (max !== null && value >= min && value < max) {
       return true;
     }
-    return max === null && value > min;
+    return max === null && value >= min;
   });
 }
```
Comment (monfera) [inline packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts:401]: Minor: this to me would be an easier read:
```
function isFilteredValue(filterRanges: Array<[number, number | null]>, value: number) {
  return filterRanges.some(([min, max]) => min <= value && value < (max ?? Infinity));
}
```
Also, should it be named `hasFilteredValue` or some such?

Comment (monfera) [reply packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts:401]: The semantics of it suggests that it returns true if at least one value falls within min/max (or min/Infinity), so maybe, `hasKeptValue` or `hasRetainedValue` is a better name. Words like keep/retain or eliminate are less ambiguous than filter; I never know if filtering refers to the kept part or the eliminated part 😄

File: packages/charts/src/chart_types/heatmap/state/selectors/geometries.ts [hunk 2]
```diff
@@ -47,11 +44,10 @@ export const geometries = createCustomCachedSelector(
...
       }),
     );
-    const { ticks } = colorScale;
-    const ranges = ticks.reduce<Array<[number, number | null]>>((acc, d, i) => {
-      if (deselectedTicks.has(d)) {
-        const rangeEnd = i + 1 === ticks.length ? null : ticks[i + 1];
-        acc.push([d, rangeEnd]);
+    const ranges = ticks.reduce<Array<[number, number | null]>>((acc, { tick }, i) => {
+      if (deselectedTicks.has(tick)) {
+        const rangeEnd = i + 1 === ticks.length ? null : ticks[i + 1].tick;
```
Comment (monfera) [inline packages/charts/src/chart_types/heatmap/state/selectors/geometries.ts:49]: Can we just use `Infinity` instead of `null`? Eliminates a union type, preserves a nice numeric type, and on 1st look, the only use is this function, which could be simplified to
```
function isFilteredValue(filterRanges: Array<[number, number | null]>, value: number) {
  return filterRanges.some(([min, max]) => min <= value && value < max);
}
```

Comment (monfera) [reply packages/charts/src/chart_types/heatmap/state/selectors/geometries.ts:49]: > i + 1 === ticks.length ?

Do we shoot for yoda conditions?

File: packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts (hunk 1 above)
Comment (markov00) [reply packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts]: thanks robert, this looks way batter e500773

File: packages/charts/src/chart_types/heatmap/state/selectors/geometries.ts (hunk 2 above)
Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/geometries.ts]: I always forgot about `Infinity` that's a great cleanup, thanks e500773

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts [hunk 3]
```diff
@@ -21,63 +20,115 @@ import {
...
+      }
+      return {
+        uniqueTicks: [...acc.uniqueTicks, formattedTick],
+        ticks: [...acc.ticks, { tick: curr, formattedTick }],
+      };
+    },
+    { uniqueTicks: [], ticks: [] },
+  );
+}
+
```
Comment (monfera) [inline packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts:80]: The cost of this is determined by `includes`, which is quadratic. Also, it makes garbage (it spreads instead of pushing). So I assume we don't expect too many ticks. Se we also don't expect too many ticks for preferring a `reduce` (which is used in a perf optimization pattern here) instead of a multi-step process, something like
```
const ticksWithFormattedTexts: Map<formattedText, tick> = ...
const ticks = ticksWithFormattedTexts.filter(...) // linear
const uniqueTicks = ticks.map(({formattedTick}) => formattedTick)
```
assuming it's necessary to return both `uniqueTicks` and `ticks` as now (one is just a lost column of the other).

In sort, not worth optimizing the code with this reduce pattern here, and if we optimize it, it's more effective to use a Map as above, than saving a linear cycle or two with `reduce`

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts [hunk 4]
```diff
@@ -21,63 +20,115 @@ import {
...
+function getQuantizedScale(spec: HeatmapSpec, heatmapTable: HeatmapTable): ScaleQuantizeType {
+  const dataExtent = spec.ranges ?? heatmapTable.extent;
+  const colors = spec.colors ?? DEFAULT_COLORS;
+  // we use the data extent or only the first two values in the `ranges` prop
+  const domain: [number, number] = [dataExtent[0], dataExtent[1]];
```
Comment (monfera) [inline packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts:85]: Is the concern that the D3 function might alter the array?

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts [hunk 5]
```diff
@@ -21,63 +20,115 @@ import {
...
+  const scale = scaleQuantize<string>().domain(domain).range(colors);
+  // quantize scale works as the linear one, we should manually
+  // compute the ticks corresponding to the quantized segments
+  const numOfSegments = colors.length;
+  const interval = (domain[1] - domain[0]) / numOfSegments;
```
Comment (monfera) [inline packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts:90]: Do we guarantee upstream that color count is nonzero, or is there no need?

Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts:90]: 😬

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts [hunk 6]
```diff
@@ -21,63 +20,115 @@ import {
...
+    ticks,
+  };
+}
+
+function getQuantileScale(spec: HeatmapSpec, heatmapTable: HeatmapTable): ScaleQuantileType {
+  const colors = spec.colors ?? DEFAULT_COLORS;
+  const domain = heatmapTable.table.map(({ value }) => value);
+  const scale = scaleQuantile<string>().domain(domain).range(colors);
+  // the ticks array should contain all quantiles + the minimum value
+  const ticks = [...new Set([heatmapTable.extent[0], ...scale.quantiles()])];
```
Comment (monfera) [inline packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts:104]: I think `scale.quantiles` used to return the internal boundaries but not the 0% quantile (provided here with `extent[0]`) or the 100%, so isn't the max extent also needed?

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts [hunk 7]
```diff
@@ -21,63 +20,115 @@ import {
...
+  };
+}
+
+function getThresholdScale(spec: HeatmapSpec, heatmapTable: HeatmapTable): ScaleThresholdType {
+  const colors = spec.colors ?? DEFAULT_COLORS;
+  const scale = scaleThreshold<number, string>()
+    .domain(spec.ranges ?? heatmapTable.extent)
+    .range(colors);
+  // the ticks array should contain all the thresholds + the minimum value
+  const ticks = [...new Set([heatmapTable.extent[0], ...scale.domain()])];
```
Comment (monfera) [inline packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts:117]: Minor: `...scale.domain()` is just the domain we passed on, right? Maybe it could be a variable named `domain`

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts [hunk 8]
```diff
@@ -21,63 +20,115 @@ import {
...
+
+  return {
+    scale,
+    ticks,
+  };
+}
+
+function getQuantileScale(spec: HeatmapSpec, heatmapTable: HeatmapTable): ScaleQuantileType {
+  const colors = spec.colors ?? DEFAULT_COLORS;
+  const domain = heatmapTable.table.map(({ value }) => value);
```
Comment (monfera) [inline packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts:101]: All these functions look like reusable `d3` scale wrappers, their applicability seems to be beyond that of heatmap. Example: quantile, quantize, threshold etc. scales for scatterplot coloring. Would it be premature to separate the D3 wrapping part from the heatmap-specific part, while putting the former outside the heatmap directory?

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts (hunk 6 above)
Comment (monfera) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts:104]: Hmm maybe these are not ticks, but band starts, so there's no need for the last one, at least not now ... in this case, maybe it'd be good to eventually name the object `band`, or some such, which could have a `start` property. No need to do it in this PR if it's intrusive to the cde, though might be forgotten as it's a small thing

File: packages/charts/src/chart_types/heatmap/state/selectors/geometries.ts (hunk 2 above)
Comment (monfera) [reply packages/charts/src/chart_types/heatmap/state/selectors/geometries.ts]: 👍 

Btw. I've no problem with yodas, I see the above commit mirrors it, I usually use/see this in our code `i === ticks.length - 1`

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts (hunk 4 above)
Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts:85]: The quantize scale takes only a two-element array and here I just picked up the first two elements

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts (hunk 8 above)
Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts:99]: I think we should postpone this in a separate PR

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts (hunk 7 above)
Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts]: done in https://github.com/elastic/elastic-charts/pull/1273/commits/0d1053e952feba7836ec7d8fbfb40e04f4c82542

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts (hunk 6 above)
Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts]: done in https://github.com/elastic/elastic-charts/pull/1273/commits/494d41f45c031979f35c47cd22ce6f46a2b00718

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts (hunk 4 above)
Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts]: I've cleaned up the code here: https://github.com/elastic/elastic-charts/commit/0d1053e952feba7836ec7d8fbfb40e04f4c82542

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts (hunk 3 above)
Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts:78]: cleaned up the code here https://github.com/elastic/elastic-charts/commit/494d41f45c031979f35c47cd22ce6f46a2b00718

**Review by rshen91 — APPROVED** [review]
LGTM tested locally. It took me an embarrassingly long time to realize dedupBands was an abbreviation of deduplicateBands. Not sure if this is something we should change.

**Review by nickofthyme — APPROVED** [review]
LGTM, tested locally.

File: packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts (hunk 1 above)
Comment (monfera) [reply packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts]: Nice change, thanks! Minor (not worth a change unless you're planning further pushes anyway): `visibilityFilterRanges` is a bit long and doesn't give away its secret, may it be shorter/clearer? Not 100% sure of the meaning, something like `visibleRanges` or `shownRanges` or `rangesToShow`?

Comment (monfera) [reply packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts]: To clarify, `visibilityFilterRanges` doesn't tell if what's inside are included or the opposite, eliminated. Unfortunately, the word `filter` is vague about what's kept and what's shed. It doesn't help that there's some compounding of name ambiguity, eg. what does "deselected" mean in `deselectedTicks` and `deselectedDataSeries`, deselected from what? 

Maybe eventually these words could be positive, ie. a list of selected/retained ticks rather than exclusions. Also, `ON_TOGGLE_SERIES_VISIBILITY` (or whatever the meaning) instead of `ON_TOGGLE_DESELECT_SERIES`; avoidance of a negative, and more meaning than "select"

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts (hunk 8 above)
Comment (monfera) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts:100]: Can we start a gh metaissue with initially just a checkbox list of such ideas? It wouldn't mean we necessarily act on it, and be non-committal of the timeline, still nice for an overview of what we may be considering, as PR comments fade from memory after the merge

**Review by monfera — APPROVED** [review]
LGTM, thanks for the changes! My comments are optional code convention ones (clearer naming) or just mentioning possible edge cases

File: packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts [hunk 9]
```diff
@@ -21,63 +20,112 @@ import {
...
-      colorScale.ticks = colorScale.config.quantiles();
-    } else if (colorScale.type === ScaleType.Threshold) {
-      colorScale.config = scaleThreshold<number, string>().domain(ranges).range(colorRange);
-      colorScale.ticks = colorScale.config.domain();
-    } else {
-      colorScale.config = scaleLinear<string>().domain(ranges).interpolate(interpolateHcl).range(colorRange);
-      colorScale.ticks = addBaselineOnLinearScale(ranges[0], ranges[1], colorScale.config.ticks(6));
-    }
-    return colorScale;
+    const { scale, bands } = SCALE_TYPE_TO_SCALE_FN[spec.colorScale ?? ScaleType.Linear](spec, heatmapTable);
```
[the remark this answers is not in the document]
Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_color_scale.ts]: done in https://github.com/elastic/elastic-charts/pull/1273/commits/f19f14bf202eb4bbb4eeb7362dd20e862b1ab403

File: packages/charts/src/chart_types/heatmap/state/selectors/compute_legend.ts [hunk 10]
```diff
@@ -12,26 +12,25 @@ import { getDeselectedSeriesSelector } from '../../../../state/selectors/get_des
...
-        key: String(tick),
-        specId: String(tick),
+        key: String(start),
+        specId: String(start),
       };
 
       return {
         color,
-        label: `> ${spec.valueFormatter ? spec.valueFormatter(tick) : tick}`,
+        label: `>${i === 0 ? '=' : ''} ${formattedStart}`,
```
[the remark this answers is not in the document]
Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/compute_legend.ts]: done in https://github.com/elastic/elastic-charts/pull/1273/commits/f19f14bf202eb4bbb4eeb7362dd20e862b1ab403

File: packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts (hunk 1 above)
Comment (markov00) [reply packages/charts/src/chart_types/heatmap/layout/viewmodel/viewmodel.ts]: You are right Robert, I've revisited the code, and correct the naming https://github.com/elastic/elastic-charts/pull/1273/commits/4228efccb7777d3b58d0e5e0c3dd3946892dbc35
I've looked more into the details and the naming was also flipped.
The `deselected...` is another story and we can chat about that in the future.

File: packages/charts/src/chart_types/heatmap/state/selectors/compute_legend.ts (hunk 10 above)
[the remark this answers is not in the document]
Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/compute_legend.ts]: The logic has changed a bit and now every item is GTE the value in the legend
https://github.com/elastic/elastic-charts/pull/1273/commits/4228efccb7777d3b58d0e5e0c3dd3946892dbc35

File: packages/charts/src/chart_types/heatmap/state/selectors/compute_legend.ts [hunk 11]
```diff
@@ -12,30 +12,29 @@ import { getDeselectedSeriesSelector } from '../../../../state/selectors/get_des
...
-
+    return bands.map(({ label, color }) => {
       return {
+        // the band label is considered unique by construction
+        seriesIdentifiers: [
+          {
+            key: label,
+            specId: label,
+          },
+        ],
```
Comment (monfera) [inline packages/charts/src/chart_types/heatmap/state/selectors/compute_legend.ts:32]: [nit] similar to how you did it below with `path`, this could be a single line, to let more "data" to be seen without scrolling

Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/compute_legend.ts]: done here https://github.com/elastic/elastic-charts/pull/1273/commits/783d46322f33bd2168b9c32a0adb40545b018860
