### PR TITLE
fix(heatmap): limit brush tool

### LINKED ISSUE #1216: The brushTool renders outside the projection area
**Describe the bug**
The `brushTool` is not constrained within the heatmap projection area

**To Reproduce**
1. Enable the brushTool visibility in the config:
```
brushTool: {
  visible: true,
}
```
2. Try to brush outside the projection area
3. The brushTool rectangle is rendered outside that area.

**Expected behaviour**
The brushTool should be constrained inside the projection area.

**Screenshots**

Jun-22-2021 20-00-25

**Version (please complete the following information):**

 - Elastic Charts: 30.x

**Additional context**
n/a

**Errors in browser console**
n/a

### PR DESCRIPTION
**Pull request by rshen91**
## Summary
This PR restricts the brush tool to the chart container so it doesn't overflow.

### Before
Jul-28-2021 broke before

### After
https://user-images.githubusercontent.com/20343860/130088001-b3235636-c0c7-47ea-9a4f-ea241e9a0dad.mp4

## Issues
Fixes #1216

### Checklist
- [x] The proper chart type label was added (e.g. :xy, :partition) if the PR involves a specific chart type
- [x] Whenever possible, please check if the closing issue is connected to a running GH project
- [x] Unit tests were updated or added to match the most common scenarios

### CODE REVIEW

File: packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts [hunk 1]
```diff
@@ -24,20 +25,38 @@ export const getBrushAreaSelector = createCustomCachedSelector(
...
+
+    const reachXAxis = containerDimensions.height < end.y + start.y;
+
     switch (brushAxis) {
       case BrushAxis.Both:
+        return {
+          top: start.y,
+          left: start.x,
+          width: end.x - start.x - chartDimensions.left,
+          height: reachXAxis ? dragShape!.height - start.y : end.y - start.y,
```
Comment (markov00) [inline packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts:58]: `dragShape` can be undefined, we should be careful here

Comment (rshen91) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts]: Thank you, good catch. I added checking for dragShape in 5fc5f9c

**Comment by rshen91** [comment]
jenkins test this

**Review by nickofthyme — APPROVED** [review]
Code LTGM.

**Comment by rshen91** [comment]
jenkins test this

**Comment by rshen91** [comment]
jenkins test this

File: packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts [hunk 2]
```diff
@@ -24,20 +25,38 @@ export const getBrushAreaSelector = createCustomCachedSelector(
...
+
+    const reachXAxis = containerDimensions.height < end.y + start.y;
+
     switch (brushAxis) {
       case BrushAxis.Both:
+        return {
+          top: start.y,
+          left: start.x,
+          width: end.x - start.x - chartDimensions.left,
+          height: reachXAxis ? dragShape.height - start.y : end.y - start.y,
```
Comment (markov00) [inline packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts:58]: As chatted on zoom, the height needs always to be computed as the `endY - startY`. The solution to fix this correctly is to limit the `endY` value from 0 to the height of the chart area computed as `gridHeightParams.gridCellHeight * gridHeightParams.pageSize`

**Review by markov00 — CHANGES_REQUESTED** [review]

File: packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts (hunk 2 above)
Comment (rshen91) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts]: thank you 🙏🏻

Comment (rshen91) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts]: Please see 08657e2!

Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts]: Hey @rshen91 it doesn't work, I'm pretty sure you are wrongly using `gridParams.height` instead of `gridParams.gridCellHeight`

Comment (rshen91) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts]: ah, my bad, sorry! Please see 206713d for updates

**Comment by rshen91** [comment]
jenkins, test this

**Comment by monfera** [comment]
Do we want to continue to sport the unusual white border around the actually selected, snapped area? I get it if it needs to be a separate PR but is there consensus toward solving it?

File: packages/charts/src/chart_types/heatmap/renderer/dom/highlighter.tsx [hunk 3]
```diff
@@ -56,13 +56,15 @@ export const HighlighterCellsComponent: FC<HighlighterCellsProps> = ({
           )}
           {brushArea.visible && (
             <>
+              {/* the rectangle box */}
```
Comment (monfera) [inline packages/charts/src/chart_types/heatmap/renderer/dom/highlighter.tsx:59]: Nice documentation embedded 😍

**Review by monfera — COMMENTED** [review]
The code changes look good!

I see a bit of grey flashing on the very bottom of the "After" version gif, toward the end of the gif recording, not sure if it means that the issue scope is not fully met, so I'm planning to approve right after the acceptability of that flashing is clarified

Not the scope of this PR, I can't vouch for the preexisting grey/white/grey banding so I'd leave it to @markov00 to consider the timing of a design update there

**Comment by rshen91** [comment]
Good call @monfera,



 no rush to approve this PR or anything, but the refactoring done since those initial screenshots seem to have fixed the issue. I'll update the after screenshot in the issue too. Here is a new giphy: 

https://user-images.githubusercontent.com/20343860/130087709-7e8de58d-f50c-42bb-8466-bb9d6999b639.mp4

File: packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts (hunk 2 above)
Comment (markov00) [reply packages/charts/src/chart_types/heatmap/state/selectors/get_brush_area.ts]: looks good now, thanks

**Review by markov00 — APPROVED** [review]
It works correctly after the last changes.
Please merge master and update the screenshots accordingly
Good to merge after that

**Review by monfera — APPROVED** [review]
LGTM! 

I's not the making or the topic of this PR, could you please create and link an issue to this PR to discuss the grey/white/grey nested selection box styling concern? I think the simplest solution would be the removal of the inner grey rectangle, which looks off, is an unusual aesthetic. But maybe there have been discussions about it
