### PR TITLE
fix: mixing bars with line or area series breaks legend toggle

### LINKED ISSUE #399: Mixing bars with line or area series breaks legend toggle
**Describe the bug**

**To Reproduce**
1. Go to https://elastic.github.io/elastic-charts/?path=/story/mixed-charts--bar-and-lines or https://elastic.github.io/elastic-charts/?path=/story/mixed-charts--areas-and-bars
1. Click to toggle the `bars` series in the legend.
1. Notice the line/area series is no longer visible.

**Expected behavior**
The line and area charts do not hide when bar series is toggled.

**Screenshots**
### Bars with line
Screen Recording 2019-09-30 at 10 31 AM

### Bars with area
Screen Recording 2019-09-30 at 10 31 AM

Also remove the `0` in upper left corner

Image 2019-09-30 at 11 23 50 AM

**Version (please complete the following information):**
 - OS: all
 - Browser: chrome/all
 - Elastic Charts: `master`

**Additional context**
The hover state works fine so must be something related to the `deselectedDataSeries` or `toggleSingleSeries` method in `chart_state.ts`

### PR DESCRIPTION
**Pull request by rshen91**
## Summary

Fixes #399 

PR410

The initial commit 4f2346e cast bandwidth in `scales.ts` in ` function computeXScale` to 0 instead of the original issue where bandwidth was being divided by 0.

Commit 209560a changed bandwidth to be `bandwidth/1` (instead of 0) which seems to be working as expected. My initial pass at this was to resolve the bug and get the x axis sizing appropriately based on the series that is visible. I plan to write or add to any unit tests but was hoping to get an initial first review to gather some feedback. Thanks!

### Checklist

Use ~~strikethroughs~~ to remove checklist items you don't feel are applicable to this PR.

- [x] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [x] This was checked for cross-browser compatibility, [including a check against IE11](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#cross-browser-compatibility)
~~- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials~~
- [x] Unit tests were updated or added to match the most common scenarios
- [x] Each commit follows the [convention](https://github.com/elastic/elastic-charts/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @rshen91, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/elastic-charts/pull/410.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by rshen91** [comment]
Note to self: I want to check on the `computeXScale` in 209560a to make sure the lines/bars/areas are adjusting correctly based on the other series not being there.

File: src/chart_types/xy_chart/utils/scales.ts [hunk 1]
```diff
@@ -100,7 +99,7 @@ export function computeXScale(options: XScaleOptions): Scale {
           range: [start, end],
         },
         {
-          bandwidth: bandwidth / totalBarsInCluster,
+          bandwidth: totalBarsInCluster > 0 ? bandwidth / totalBarsInCluster : bandwidth / 1,
```
Comment (markov00) [inline src/chart_types/xy_chart/utils/scales.ts]:
```suggestion
          bandwidth: totalBarsInCluster > 0 ? bandwidth / totalBarsInCluster : bandwidth,
```

Comment (markov00) [inline src/chart_types/xy_chart/utils/scales.ts]:
```suggestion
          bandwidth: totalBarsInCluster > 0 ? bandwidth / totalBarsInCluster : bandwidth,


```
