### PR TITLE
fix(annotation): render annotations correctly based on passed handlers

### LINKED ISSUE #1969: Annotation are rendered always as buttons
**Describe the issue**
There is a bug that wraps the annotation icons always within a `button`.
The `onDOMElementClick` of the `LineMarker` component is always configured and doesn't depends if the `onAnnotationClick` handler is configured or not in the `Settings`

**To Reproduce**
1. Go to https://elastic.github.io/elastic-charts/?path=/story/annotations-lines--x-continuous-domain&globals=theme:light
2. Click on the annotation icon
3. There is no event but the icon is clickable.

**Expected behaviour**
The annotation icon is clickable only if we have an associated `onAnnotationClick` event.

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/151556

**Checklist**
- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] Every related Kibana issue is listed under `Kibana Cross Issues` list and the `kibana cross issue` tag is applied

### PR DESCRIPTION
**Pull request by dej611**
## Summary

Annotations with no click handlers configured are no longer shown as interactive.

Screenshot 2023-02-23 at 18 25 38

## Issues

fix #1969 

### Checklist

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] All related issues have been linked (i.e. `closes #123`, `fixes #123`)

### CODE REVIEW

File: packages/charts/src/chart_types/xy_chart/renderer/dom/annotations/line_marker.tsx [hunk 1]
```diff
@@ -119,7 +119,7 @@ export function LineMarker({
   void popper?.current?.update?.();
 
   // want it to be tabbable if interactive if there is a click handler
-  return onDOMElementClick ? (
+  return clickable && onDOMElementClick ? (
```
Comment (markov00) [inline packages/charts/src/chart_types/xy_chart/renderer/dom/annotations/line_marker.tsx:122]: you can also remove the `onDOMElementClick` check because this always exists

Comment (dej611) [reply packages/charts/src/chart_types/xy_chart/renderer/dom/annotations/line_marker.tsx:122]:
```suggestion
  return clickable ? (
```

**Review by markov00 — APPROVED** [review]
Tested locally, LGTM
