### PR TITLE
fix(axis): ordinal number ending fix for the weekly resolution

### LINKED ISSUE #1633: [Axis] The new time axis displays wrong text for the dates with 1s
**Describe the issue**
On the new time axis there are cases that the dates with 1s are displayed wrongly. For example 1th of March instead of 1st of March.

**To Reproduce**
1. Initialize kibana locally
2. Click on Lens
3. Create a bar chart with the flights dataset
4. Use a 30 days timespan
5. Check the x axis

image

you can see the 21th here

If you change the timespan to 7 days you can see that is displayed correctly
image

**Expected behaviour**
It should be 1st in all cases

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/128504

**Checklist**
- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] Every related Kibana issue is listed under `Kibana Cross Issues` list and the `kibana cross issue` tag is applied

### PR DESCRIPTION
**Pull request by monfera**
## Summary

Besides fixing the weeklies, the following improvements are made:
- DRY: reference the same formatter for daily minors and day minors of week starting days
- the `st` `nd` `rd` `th` got generalized to arbitrary integers (ie. beyond 31, and negatives too) for future reuse
- image tests lock in the proper endings

image

## Details

HT @markov00 for reporting this issue before integration 🙇 — I fixed it for the days but not for the weeks.

## Issues

Fix #1633

Addresses https://github.com/elastic/kibana/issues/128504 

### Checklist

- [X] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [X] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [X] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [X] The proper documentation and/or storybook story has been added or updated
- [X] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)

### CODE REVIEW

File: packages/charts/src/chart_types/xy_chart/axes/timeslip/rasters.ts [hunk 1]
```diff
@@ -86,15 +86,29 @@ const hourFormat: Partial<ConstructorParameters<typeof Intl.DateTimeFormat>[1]>
...
 };
 
+const englishOrdinalEndings = ['th', 'st', 'nd', 'rd', 'th'];
+const englishOrdinalEnding = (signedNumber: number) => {
+  const n = Math.abs(signedNumber);
+  const ones = n % 10;
+  const tens = Math.floor(n / 10) % 10;
+  return tens === 1 ? 'th' : englishOrdinalEndings[Math.min(ones, 4)];
+};
+
```
Comment (markov00) [inline packages/charts/src/chart_types/xy_chart/axes/timeslip/rasters.ts:96]: nit: This can be replaced by `Intl.PluralRules`. In this case I don't have an idea of how better it will perform and if this can be useful in the future.

```
const englishOrdinalEnding = (signedNumber: number) => {
const suffixMap = {
  one: 'st',
  two: 'nd',
  few: 'rd',
  other: 'th',
};
return suffixMap[new Intl.PluralRules('en-US', { type: 'ordinal' }).select(signedNumber)];
```

File: storybook/parameters.ts [hunk 2]
```diff
@@ -84,7 +84,7 @@ export const storybookParameters: Parameters = {
         // See integration/jest_puppeteer.config.js#L19-L22
         name: 'VRT Viewport',
         styles: {
-          width: '800px',
+          width: '785px',
```
Comment (markov00) [inline storybook/parameters.ts:87]: to @nickofthyme this is the actual size of a VRT viewport without considering the `paddings`

**Review by markov00 — APPROVED** [review]
LGTM

File: packages/charts/src/chart_types/xy_chart/axes/timeslip/rasters.ts (hunk 1 above)
Comment (monfera) [reply packages/charts/src/chart_types/xy_chart/axes/timeslip/rasters.ts]: 5aa6ff98226ac9e99637c1f127f0388f3e998ef9

File: packages/charts/src/chart_types/xy_chart/axes/timeslip/rasters.ts [hunk 3]
```diff
@@ -86,13 +86,16 @@ const hourFormat: Partial<ConstructorParameters<typeof Intl.DateTimeFormat>[1]>
...
+const englishOrdinalEndings = {
+  zero: 'th',
+  one: 'st',
+  two: 'nd',
+  few: 'rd',
+  many: 'th',
+  other: 'th',
 };
+const englishPluralRules = new Intl.PluralRules('en-US', { type: 'ordinal' });
+const englishOrdinalEnding = (signedNumber: number) => englishOrdinalEndings[englishPluralRules.select(signedNumber)];
```
Comment (nickofthyme) [inline packages/charts/src/chart_types/xy_chart/axes/timeslip/rasters.ts:98]: 😍

File: packages/charts/src/chart_types/xy_chart/axes/timeslip/rasters.ts (hunk 1 above)
Comment (monfera) [reply packages/charts/src/chart_types/xy_chart/axes/timeslip/rasters.ts]: Added this, a cursory test on 4 million numbers in a tight loop didn't show an obvious perf issue, and not only is it more elegant, but also, a nice track for adding the same in more languages. Standard API > code
